flows:
  s1:
    name: 标准流程1
    description: ''
    left_table: raw_sap_monthly_data
    right_table: 物料主数据
    join_type: left
    active_col: is_active
    steps:
    - name: 匹配物料主数据
      left_table: raw_sap_monthly_data
      right_table: 物料主数据
      join_type: left
      unmatched: mark_exception
      keys:
      - left: material_code
        right: material_code
      output_fields: &id001
      - 物料组
      - material_desc
      - brand
      - 型号
      - 项目名
      - 工厂机型类别
      - process_category
      - model_category
      - standard_type
    priority_specs:
    - priority: 1
      keys:
      - left: material_code
        right: material_code
    output_fields: *id001
    unmatched: mark_exception
