exports:
- export_id: EXPORT_202503_20260518_202845
  period: '202503'
  merge_run_id: MERGE_s1_20260518_180005
  flow_name: 标准流程1
  import_batch_id: SAP_202502_20260518_175735
  file_name: processing_fee_export_202503_20260518_202845.xlsx
  file_path: data/output/processing_fee_exports/202503/processing_fee_export_202503_20260518_202845.xlsx
  row_count: '54'
  field_count: '11'
  fields:
  - yyyymm
  - factory_code
  - factory_name
  - material_code
  - material_desc
  - brand
  - model_category
  - process_category
  - standard_type
  - delivery_qty
  - movement_type
  created_at: '2026-05-18T20:28:46.024221'
- export_id: EXPORT_202503_20260518_202413
  period: '202503'
  merge_run_id: MERGE_s1_20260518_180005
  flow_name: 标准流程1
  import_batch_id: SAP_202502_20260518_175735
  file_name: processing_fee_export_202503_20260518_202413.xlsx
  file_path: data/output/processing_fee_exports/202503/processing_fee_export_202503_20260518_202413.xlsx
  row_count: '54'
  field_count: '14'
  fields:
  - yyyymm
  - factory_code
  - factory_name
  - material_code
  - material_desc
  - brand
  - model_category
  - process_category
  - standard_type
  - delivery_qty
  - order_no
  - legal_entity_code
  - material_group
  - delivery_qty_original
  created_at: '2026-05-18T20:24:13.684019'
- export_id: EXPORT_202503_20260518_201019
  period: '202503'
  merge_run_id: MERGE_s1_20260518_180005
  flow_name: 标准流程1
  import_batch_id: SAP_202502_20260518_175735
  file_name: processing_fee_export_202503_20260518_201019.xlsx
  file_path: data/output/processing_fee_exports/202503/processing_fee_export_202503_20260518_201019.xlsx
  row_count: '54'
  field_count: '11'
  fields:
  - yyyymm
  - factory_code
  - factory_name
  - material_code
  - material_desc
  - brand
  - model_category
  - process_category
  - standard_type
  - delivery_qty
  - source_file_name
  created_at: '2026-05-18T20:10:19.601921'
